### ISSUE TITLE
No teleportation after the training session

### ISSUE THREAD

**Issue by LBrinkmann** [nthByte-LLC/iron-craft#30]
<img width="854" alt="Screenshot 2022-03-25 at 16 20 37" src="https://user-images.githubusercontent.com/15154401/160149829-64f4ee10-bf28-4f81-b1ae-4b69b64ccc8b.png">

**Comment by its-c10** [comment]
No clue why this occurs to be honest. May just re-write the whole prompt system entirely with a different library  so that I have more control and oversee as to what's actually going on behind the hood because the it's sort of difficult to see what's going on behind the scenes with the current player input API i am using.
